### ISSUE TITLE
Handling missing start or end of rains values when performing other calculations

### ISSUE THREAD

**Issue by lilyclements** [IDEMSInternational/rpicsa#2]
A query has come up when we have a missing start or end of rains value in some functions. @rdstern would you mind having a look at these questions since they relate to Start and End of Rains:

1. Presumably, if at least one of start or end of rains is missing for `seasonal_length`, then we give an `NA` value for the seasonal length. Is this the case?
2. Presumably, if at least one of start or end of rains is missing for `seasonal_rain`, then we give an `NA` value for the seasonal rainfall. Is this the case?
3. How should we handle missing values in the `crop_success_probabilities` function if the start (or end) of rains is missing? This function works like the `Climatic > PICSA > Crops` function in R-Instat.
4. How should we handle missing values in the `season_start_probabilities` function if the start of rains is missing? (The probabilities of the start of the rains occurring on or before a set of specified DOYs - I think this is in R-Instat under `Climatic > PICSA > Crops` as well but I might be wrong).

**Comment by rdstern** [comment]
> A query has come up when we have a missing start or end of rains value in some functions. @rdstern would you mind having a look at these questions since they relate to Start and End of Rains:
> 
> 1. Presumably, if at least one of start or end of rains is missing for `seasonal_length`, then we give an `NA` value for the seasonal length. Is this the case?  
RDS: I think so, and hope so.
> 2. Presumably, if at least one of start or end of rains is missing for `seasonal_rain`, then we give an `NA` value for the seasonal rainfall. Is this the case?
RDS: Exactly
> 3. How should we handle missing values in the `crop_success_probabilities` function if the start (or end) of rains is missing? This function works like the `Climatic > PICSA > Crops` function in R-Instat.
RDS: That year should then be missing in the calculations
> 4. How should we handle missing values in the `season_start_probabilities` function if the start of rains is missing? (The probabilities of the start of the rains occurring on or before a set of specified DOYs - I think this is in R-Instat under `Climatic > PICSA > Crops` as well but I might be wrong).
RDS: Again, then omit that year.
